version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
      - "8001:8001"  #RedisInsight (Web UI)
    volumes:
      - redis-stack:/data
    restart: always
volumes:
  redis-stack:
